application: tattooports
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest

builtins:
- appstats: on
- deferred: on

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /gadmin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /admin/settings.*
  script: admin_settings.app
  login: admin
- url: /admin/models.*
  script: admin_models.app
  login: admin
- url: /admin/content.*
  script: admin_content.app
  login: admin
- url: /admin.*
  script: admin.app
  login: admin
- url: /.*
  script: main.app
  login: admin

admin_console:
  pages:
  - name: appstats
    url: /stats